export interface Course {
  "순번": number
  "학기": string
  "대학(원)": string
  "학과(부)": string
  "학년": string
  "이수구분": string
  "이수영역": string
  "학수번호": string
  "교과목명": string
  "교과목명(영문)": string
  "담당교수": string
  "소속": string
  "강의실": string
  "시간표(교시)": string
  "시간표(시간)": string
  "교시유형": string
  "학점": number
  "시수": number
  "이론": number
  "실습": number
  "정원": number
  "수강": number
  "수강(남)": number
  "수강(여)": number
  "재수강": number
  "수업구분": string
  "수업유형": string
  "집중이수제": string
  "성적평가": string
  "원어강의": string
  "원어강의구분": string
  "원어강사료지급": string
  "캡스톤디자인": string
  "수강대상": string
  "수업방법": string
  "비고": string
}
